# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxBQd6K3fbNfJIY3nzTQLDuxuQZzizoL
"""

import pandas as pd

data = [
    (101, '2024-03-01', 'Absent'),
    (101, '2024-03-02', 'Absent'),
    (101, '2024-03-03', 'Absent'),
    (101, '2024-03-04', 'Absent'),
    (101, '2024-03-05', 'Present'),
    (102, '2024-03-02', 'Absent'),
    (102, '2024-03-03', 'Absent'),
    (102, '2024-03-04', 'Absent'),
    (102, '2024-03-05', 'Absent'),
    (103, '2024-03-05', 'Absent'),
    (103, '2024-03-06', 'Absent'),
    (103, '2024-03-07', 'Absent'),
    (103, '2024-03-08', 'Absent'),
    (103, '2024-03-09', 'Absent'),
    (104, '2024-03-01', 'Present'),
    (104, '2024-03-02', 'Present'),
    (104, '2024-03-03', 'Absent'),
    (104, '2024-03-04', 'Present'),
    (104, '2024-03-05', 'Present'),
]

df=pd.DataFrame(data,columns=['student_id','attendance_date','status'])

def abcount(df):
   absent_df=df[df['status']=='Absent']
   return absent_df

print(abcount(df))

students_data = {
    'student_id': [101, 102, 103, 104, 105],
    'student_name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'David Lee', 'Eva White'],
    'class': ['5th Grade', '6th Grade', '5th Grade', '6th Grade', '5th Grade'],
    'age': [10, 11, 10, 12, 10]
}

parent_contacts_data = {
    'student_id': [101, 102, 103, 104, 105],
    'parent_email': ['alice_parent@example.com', 'bob_parent@example.com', 'invalid_email.com', 'invalid_email.com', 'eva_white@example.com']
}

students_df = pd.DataFrame(students_data)
parent_contacts_df = pd.DataFrame(parent_contacts_data)

print(abcount(df),students_df,parent_contacts_df)